### ISSUE TITLE
NaN in Wave Function Optimization

### ISSUE THREAD

**Issue by fabian-sp** [NLESC-JCER/QMCTorch#170]
Hi,

I am trying to run the tutorial example Wave Function Optimization in a Colab. I am running into NaN immediately:

```
INFO:QMCTorch|
INFO:QMCTorch|  Optimization
INFO:QMCTorch|  Task                :
INFO:QMCTorch|  Number Parameters   : 15
INFO:QMCTorch|  Number of epoch     : 50
INFO:QMCTorch|  Batch size          : 5000
INFO:QMCTorch|  Loss function       : energy
INFO:QMCTorch|  Clip Loss           : False
INFO:QMCTorch|  Gradients           : manual
INFO:QMCTorch|  Resampling mode     : update
INFO:QMCTorch|  Resampling every    : 1
INFO:QMCTorch|  Resampling steps    : 25
INFO:QMCTorch|  Output file         : H2_pyscf_sto-3g_QMCTorch.hdf5
INFO:QMCTorch|  Checkpoint every    : None
INFO:QMCTorch|
INFO:QMCTorch|
INFO:QMCTorch|  epoch 0
INFO:QMCTorch|Error : Nan detected in local energy
```

The bug is similar to the one reported in https://github.com/NLESC-JCER/QMCTorch/issues/169.

Could you explain how to fix this, or provide a minimal working example?

**Comment by PGaneshIyer** [comment]
This is for H2 in wf optimization example provided.  Acceptance ratio is zero, producing NANs in total energy.  Adjusting params of sampler does not help.  

INFO:QMCTorch|
INFO:QMCTorch| SCF Calculation
INFO:QMCTorch|  Reusing scf results from H2_pyscf_sto-6g.hdf5
INFO:QMCTorch|
INFO:QMCTorch| Wave Function
INFO:QMCTorch|  Jastrow factor      : True
INFO:QMCTorch|  Jastrow kernel      : PadeJastrowKernel
INFO:QMCTorch|  Highest MO included : 2
INFO:QMCTorch|  Configurations      : single_double(2,2)
INFO:QMCTorch|  Number of confs     : 4
INFO:QMCTorch|  Kinetic energy      : jacobi
INFO:QMCTorch|  Number var  param   : 27
INFO:QMCTorch|  Cuda support        : False
INFO:QMCTorch|
INFO:QMCTorch| Monte-Carlo Sampler
INFO:QMCTorch|  Number of walkers   : 5000
INFO:QMCTorch|  Number of steps     : 200
INFO:QMCTorch|  Step size           : 0.2
INFO:QMCTorch|  Thermalization steps: -1
INFO:QMCTorch|  Decorelation steps  : 100
INFO:QMCTorch|  Walkers init pos    : atomic
INFO:QMCTorch|  Move type           : all-elec
INFO:QMCTorch|  Move proba          : normal
INFO:QMCTorch|
INFO:QMCTorch| QMC Solver 
INFO:QMCTorch|  WaveFunction        : SlaterJastrow
INFO:QMCTorch|  Sampler             : Metropolis
INFO:QMCTorch|  Optimizer           : Adam
INFO:QMCTorch|
INFO:QMCTorch|  Single Point Calculation : 5000 walkers | 200 steps
INFO:QMCTorch|  Sampling: 100%|██████████| 200/200 [00:00<00:00, 286.61it/s]
INFO:QMCTorch|   Acceptance rate     : 0.00 %
INFO:QMCTorch|   Timing statistics   : 286.47 steps/sec.
INFO:QMCTorch|   Total Time          : 0.70 sec.
INFO:QMCTorch|  Energy   : nan +/- nan
INFO:QMCTorch|  Variance : nan
INFO:QMCTorch|
INFO:QMCTorch|  Optimization
INFO:QMCTorch|  Task                :
INFO:QMCTorch|  Number Parameters   : 9
INFO:QMCTorch|  Number of epoch     : 50
INFO:QMCTorch|  Batch size          : 5000
INFO:QMCTorch|  Loss function       : energy
INFO:QMCTorch|  Clip Loss           : False
INFO:QMCTorch|  Gradients           : manual
INFO:QMCTorch|  Resampling mode     : update
INFO:QMCTorch|  Resampling every    : 1
INFO:QMCTorch|  Resampling steps    : 25
INFO:QMCTorch|  Output file         : H2_pyscf_sto-6g_QMCTorch.hdf5
INFO:QMCTorch|  Checkpoint every    : None
INFO:QMCTorch|
INFO:QMCTorch|
INFO:QMCTorch|  epoch 0
INFO:QMCTorch|Error : Nan detected in local energy

**Comment by NicoRenaud** [comment]
Thanks a lot and sorry for the late notice, I've missed the GH notification. 
I'll take a look at the issue this week and report back

**Comment by NicoRenaud** [comment]
Hey @fabian-sp and @PGaneshIyer , 

I've fixed a few warnings that were flagged in another issue in the branch `issue170`. The test are passing on GH Action ([here](https://github.com/NLESC-JCER/QMCTorch/actions/runs/12181381622/job/33977897862)). Could you tell me two things:

- which OS are you using ? I've only tested the code on Ubuntu so the code might misbehave on OSX
- do you remember how you installed qmctorch ? Did you use the pip release or did you clone the repo and pip installed it ?

Thanks again for your help !

**Comment by NicoRenaud** [comment]
I've fixed the issue that caused the NaN in the energy and merge the changes in master. 
I think that should solve your problem. Thanks for filing an issue !
