### ISSUE TITLE
Indexing error when loading molecule xyz file.

### ISSUE THREAD

**Issue by Rik-Breebaart** [NLESC-JCER/QMCTorch#29]
There is a indexing error when loading the water.xyz file in example/single_point/h2o_sampling.py

**Comment by NicoRenaud** [comment]
that works fine for me. could you paste the error message ?

**Comment by Rik-Breebaart** [comment]
Traceback (most recent call last):
  File "/home/breebaart/dev/QMCTorch/example/single_point/h2o_sampling.py", line 7, in <module>
    mol = Molecule(atom= water.xyz, unit='angs',
NameError: name 'water' is not defined
breebaart@ccpgate:~/dev/QMCTorch$ /usr/bin/python /home/breebaart/dev/QMCTorch/example/single_point/h2o_sampling.py
Traceback (most recent call last):
  File "/home/breebaart/dev/QMCTorch/example/single_point/h2o_sampling.py", line 8, in <module>
    calculator='pyscf', basis='sto-3g', name='water')
  File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 60, in __init__
    self._process_atom_str()
  File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 134, in _process_atom_str
    self._get_atomic_properties(atoms)
  File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 147, in _get_atomic_properties
    x, y, z = float(atom_data[1]), float(
IndexError: list index out of range

**Comment by NicoRenaud** [comment]
well it seems that the quotes around water.xyz disappeared ... They are there in the repo though, so I guess you removed them ?

Just to be explicit you see to have
```python 
mol = Molecule(atom= water.xyz, unit='angs',
```

where you need 

```python
mol = Molecule(atom= 'water.xyz', unit='angs',
```

**Comment by Rik-Breebaart** [comment]
Ah yes, I first removed them, and changed the line to the atom coordinates. The second part of the error is what I get when using 'water.xyz'.
The error is:

> Traceback (most recent call last):
>   File "/home/breebaart/dev/QMCTorch/example/single_point/h2o_sampling.py", line 8, in <module>
>     calculator='pyscf', basis='sto-3g', name='water')
>   File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 60, in __init__
>     self._process_atom_str()
>   File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 134, in _process_atom_str
>     self._get_atomic_properties(atoms)
>   File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 147, in _get_atomic_properties
>     x, y, z = float(atom_data[1]), float(
> IndexError: list index out of range

**Comment by NicoRenaud** [comment]
can you paste the content of the water.xyz file ?

**Comment by Rik-Breebaart** [comment]
This is the content of the water.xyz file:
> 3
> water molecule
> O	 0.000000 0.00000  0.00000
> H 	 0.758602 0.58600  0.00000
> H	-0.758602 0.58600  0.00000
>

**Comment by NicoRenaud** [comment]
is there a blank line after the last H ?

**Comment by Rik-Breebaart** [comment]
yes

**Comment by Rik-Breebaart** [comment]
It was a issue from my path, running with the right path as input fixed the problem
