### ISSUE TITLE
Backpropagation error, gradient computation has been modified by inplace operation.

### ISSUE THREAD

**Issue by Rik-Breebaart** [NLESC-JCER/QMCTorch#30]
Backpropagation error for molecules other then H2 when optimizing. Error: One of the variables needed for gradient computation has been modified by an inplace operation.

**Comment by NicoRenaud** [comment]
that works fine for me for LiH. Could you paste the python script and the error message ?

**Comment by Rik-Breebaart** [comment]
The script:


> #ADF test
> import sys
> sys.path.insert(0,"/home/breebaart/dev/QMCTorch/")
> from torch import optim
> from qmctorch.wavefunction import Orbital, Molecule
> from qmctorch.solver import SolverOrbital
> from qmctorch.sampler import Metropolis
> from qmctorch.utils import set_torch_double_precision
> from matplotlib import pyplot as plt
> import numpy as np
> from qmctorch.utils import (plot_energy, plot_data)
> import time
> 
> # bond distance : 0.74 A -> 1.38 a
> # optimal H positions +0.69 and -0.69
> # ground state energy : -31.688 eV -> -1.16 hartree
> # bond dissociation energy 4.478 eV -> 0.16 hartree
> 
> 
> 
> set_torch_double_precision()
> 
> # define the molecule
> molFile = 1
> filename = ["C1O2_adf_dzp", "H1Li1_adf_dzp", "H2_adf_dzp"] 
> fileloc = "/home/breebaart/dev/QMCTorch/TrainingExaminig/hdf5/"
> mol = Molecule(load=fileloc+filename[molFile]+ ".hdf5")
> # define the wave function
> wf = Orbital(mol, kinetic='jacobi',
>              configs='single_double(2,2)',
>              use_jastrow=True)
> 
> wf.jastrow.weight.data[0] = 1.
> 
> # sampler
> sampler = Metropolis(nwalkers=200,
>                      nstep=200, step_size=0.2,
>                      ntherm=-1, ndecor=100,
>                      nelec=wf.nelec, init=mol.domain('atomic'),
>                      move={'type': 'all-elec', 'proba': 'normal'})
> 
> 
> # optimizer
> lr_dict = [{'params': wf.jastrow.parameters(), 'lr': 3E-3},
>            {'params': wf.ao.parameters(), 'lr': 1E-6},
>            {'params': wf.mo.parameters(), 'lr': 1E-3},
>            {'params': wf.fc.parameters(), 'lr': 2E-3}]
> opt = optim.Adam(lr_dict, lr=1E-3)
> 
> # scheduler
> scheduler = optim.lr_scheduler.StepLR(opt, step_size=100, gamma=0.90)
> 
> # QMC solver
> solver = SolverOrbital(wf=wf, sampler=sampler,
>                        optimizer=opt, scheduler=None)
> 
> # perform a single point calculation
> obs = solver.single_point()
> 
> # optimize the wave function
> solver.configure(task='wf_opt', freeze=['ao', 'mo'])
> solver.track_observable(['local_energy'])
> 
> solver.configure_resampling(mode='update',
>                             resample_every=1,
>                             nstep_update=50)
> solver.ortho_mo = False
> toc = time.time()
> obs = solver.run(250, batchsize=None,
>                  loss='energy',
>                  grad='auto',
>                  clip_loss=False)
> tic = time.time()
> print("solver run time: {} ".format(tic-toc))
> plot_energy(obs.local_energy, show_variance=False,path= "/home/breebaart/dev/QMCTorch/TrainingExaminig/Figures/"+filename[molFile])
> plot_data(solver.observable, obsname='jastrow.weight',path= "/home/breebaart/dev/QMCTorch/TrainingExaminig/Figures/"+filename[molFile]+"_data")
> 

Where I got the error message: 

> Traceback (most recent call last):
>   File "/home/breebaart/dev/QMCTorch/TrainingExaminig/ADF_tests.py", line 71, in <module>
>     clip_loss=False)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/solver/solver_orbital.py", line 107, in run
>     loss, eloc = self.evaluate_gradient(lpos)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/solver/solver_orbital.py", line 168, in evaluate_grad_auto
>     loss.backward()
>   File "/usr/lib/python3.6/torch/tensor.py", line 198, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/usr/lib/python3.6/torch/autograd/__init__.py", line 100, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.DoubleTensor [200, 3, 12]], which is output 0 of ProdBackward1, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> breebaart@ccpgate:~/dev/QMCTorch$ 

and with torch.autograd.set_detect_anomaly(True):

> Warning: Error detected in ProdBackward1. Traceback of forward call that caused the error:
>   File "/home/breebaart/dev/QMCTorch/TrainingExaminig/ADF_tests.py", line 73, in <module>
>     clip_loss=False)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/solver/solver_orbital.py", line 107, in run
>     loss, eloc = self.evaluate_gradient(lpos)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/solver/solver_orbital.py", line 160, in evaluate_grad_auto
>     loss, eloc = self.loss(lpos)
>   File "/usr/lib/python3.6/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/utils/torch_utils.py", line 132, in forward
>     local_energies = self.wf.local_energy(pos)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/wavefunction/wf_orbital.py", line 202, in local_energy_jacobi
>     ke = self.kinetic_energy_jacobi(pos)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/wavefunction/wf_orbital.py", line 225, in kinetic_energy_jacobi
>     bkin = self.get_kinetic_operator(x, mo=mo)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/wavefunction/wf_orbital.py", line 265, in get_kinetic_operator
>     d2jast = self.jastrow(x, derivative=2) / jast
>   File "/usr/lib/python3.6/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/wavefunction/fast_jastrow.py", line 149, in forward
>     return self._jastrow_second_derivative(r, dr, d2r, jast)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/wavefunction/fast_jastrow.py", line 218, in _jastrow_second_derivative
>     djast, out_mat=hess_jast)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/wavefunction/fast_jastrow.py", line 387, in _partial_derivative
>     x = x.prod(-1)
>  (print_stack at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:60)
> Traceback (most recent call last):
>   File "/home/breebaart/dev/QMCTorch/TrainingExaminig/ADF_tests.py", line 73, in <module>
>     clip_loss=False)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/solver/solver_orbital.py", line 107, in run
>     loss, eloc = self.evaluate_gradient(lpos)
>   File "/home/breebaart/dev/QMCTorch/qmctorch/solver/solver_orbital.py", line 168, in evaluate_grad_auto
>     loss.backward()
>   File "/usr/lib/python3.6/torch/tensor.py", line 198, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/usr/lib/python3.6/torch/autograd/__init__.py", line 100, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.DoubleTensor [200, 3, 12]], which is output 0 of ProdBackward1, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by NicoRenaud** [comment]
can you replace `grad='auto'` by `grad='manual'` ? in `solver.run()`
Just to be explicit replace :

```python
obs = solver.run(250, batchsize=None,
                  loss='energy',
                  grad='auto',
                  clip_loss=False)
```
by 
```python
obs = solver.run(250, batchsize=None,
                  loss='energy',
                  grad='manual',
                  clip_loss=False)
```

**Comment by Rik-Breebaart** [comment]
Yes, that fixes it.

**Comment by NicoRenaud** [comment]
Ok I know what the issue is then ! I'll fix that thanks !
