### ISSUE TITLE
adf kffile read error in kftools

### ISSUE THREAD

**Issue by Rik-Breebaart** [NLESC-JCER/QMCTorch#31]
When using adf I optain a error from the calculator/adf.py file for kffile.read. This is probably a error on my side with regards to the plams package.
The error I obtain when using adf as calculator:

> Traceback (most recent call last):
>   File "/home/breebaart/dev/QMCTorch/example/optimization/h2.py", line 20, in <module>
>     unit='bohr')
>   File "/usr/lib/python3.6/qmctorch/wavefunction/molecule.py", line 78, in __init__
>     self.basis = self.calculator.run()
>   File "/usr/lib/python3.6/qmctorch/wavefunction/calculator/adf.py", line 40, in run
>     basis = self.get_basis_data(t21_path)
>   File "/usr/lib/python3.6/qmctorch/wavefunction/calculator/adf.py", line 85, in get_basis_data
>     basis.TotalEnergy = kf.read('Total Energy', 'Total energy')
>   File "/home/breebaart/.local/lib/python3.6/site-packages/scm/plams/tools/kftools.py", line 301, in read
>     ret = self.reader.read(section, variable)
> AttributeError: 'NoneType' object has no attribute 'read'

**Comment by NicoRenaud** [comment]
yes I think the PLAMS library is not linked properly. Could you execute the following :
```python
from scm import plams
print(plams.KFFile)
```

**Comment by Rik-Breebaart** [comment]
This returns: 
<class 'scm.plams.tools.kftools.KFFile'>

**Comment by NicoRenaud** [comment]
are you also running that from VSCode ? Because then the path of the ADF output file (Tape21 file) file will be all wrong.

**Comment by Rik-Breebaart** [comment]
Yes, I am running from VSCode.

**Comment by NicoRenaud** [comment]
and in the terminal you are in the directory where the python script is ?

**Comment by NicoRenaud** [comment]
I think it's because your ADF calculation failed. Not because of QMCTorch. Did you run a simple ADF calculation to check that it was working ?

**Comment by Rik-Breebaart** [comment]
The ADF calculation from the PLAMS toturial fails so it indeed is an error in my ADF calculation

**Comment by NicoRenaud** [comment]
If you paste the error you get I can maybe help
